"""empty message

Revision ID: 09bff0b9175e
Revises: d58a53f6c1d3
Create Date: 2022-03-10 14:54:01.050187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09bff0b9175e'
down_revision = 'd58a53f6c1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('ignore', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('albums', sa.Column('album_type', sa.Enum('SMART', 'MANUAL', 'EVENT', 'PEOPLE', name='albumtype'), nullable=True))
    op.execute("update albums set album_type='SMART' where smart=1")
    op.drop_column('albums', 'smart')
    op.add_column('status', sa.Column('find_events_needed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('smart', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.execute("update albums set smart=1 where album_type='SMART'")
    op.drop_column('status', 'find_events_needed')
    op.drop_column('albums', 'album_type')
    op.drop_table('event')
    # ### end Alembic commands ###
