"""empty message

Revision ID: 76504f089bd4
Revises: ebc46c3a676e
Create Date: 2023-10-03 17:57:45.413879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76504f089bd4'
down_revision = 'ebc46c3a676e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('faces_all_identified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'faces_all_identified')
    # ### end Alembic commands ###
