"""empty message

Revision ID: ebc46c3a676e
Revises: 192e728d2c5d
Create Date: 2023-07-17 18:44:48.404309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc46c3a676e'
down_revision = '192e728d2c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faces', sa.Column('updated', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_faces_updated'), 'faces', ['updated'], unique=False)
    op.execute('ALTER TABLE faces MODIFY COLUMN updated TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faces_updated'), table_name='faces')
    op.drop_column('faces', 'updated')
    # ### end Alembic commands ###
